import{a as u,i as l,S as f}from"./assets/vendor-b2578120.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();const h="43046447-8272f873c9098dbfa2cb53d4e",y="https://pixabay.com/api/";async function p(o,e,t){try{return(await u.get(y,{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:t}})).data}catch(i){throw console.error("Error fetching images:",i),i}}function g(o){if(o.length===0)l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const e=o.map(t=>`<li class="photos-block">
            <a class="photos-link" href="${t.largeImageURL}">
            <img class="photo" src="${t.webformatURL}" alt="${t.tags}"/>
            </a>
            <ul class="photo-data">
            <li class="photo-data-detail"><p><span class="info">Likes</span></br>${t.likes}</p></li>
            <li class="photo-data-detail"><p><span class="info">Views</span></br>${t.views}</p></li>
            <li class="photo-data-detail"><p><span class="info">Comments</span></br>${t.comments}</p></li>
            <li class="photo-data-detail"><p><span class="info">Downloads</span></br>${t.downloads}</p></li>
            </ul>
            </li>`).join("");a.galleryList.insertAdjacentHTML("beforeend",e),L.refresh()}}const a={searchForm:document.querySelector(".search-form"),inputElement:document.querySelector(".search-input"),load:document.querySelector(".load"),galleryList:document.querySelector(".gallery"),loader:document.querySelector(".loader")},L=new f(".gallery a",{captionsData:"alt",captionDelay:250});let c,n=1;const m=15;a.searchForm.addEventListener("submit",b);async function b(o){if(o.preventDefault(),c=a.inputElement.value.trim(),n=1,a.galleryList.innerHTML="",c===""){l.error({title:"Error",message:"Please enter a search term.",position:"topRight"});return}try{const e=await p(c,n,m),t=e.totalHits;if(e.hits.length===0){a.galleryList.innerHTML="",l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}else g(e.hits),a.inputElement.value="";m*n>=t}catch(e){console.error("Error fetching images:",e),l.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{}}a.load.addEventListener("click",async()=>{try{a.load&&(n+=1);const o=await p(c,n,m),e=o.totalHits;g(o.hits),E(),m*n>=e;const t=a.galleryList.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*3,behavior:"smooth"})}catch(o){console.error("Error fetching more images:",o),l.error({title:"Error",message:`Error fetching more images: ${o}`})}finally{}});function E(){a.load.removeAttribute("disabled")}
//# sourceMappingURL=commonHelpers.js.map
